name: Crawler Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U .
          #- name: Prepare credentials
          #run: |
          #bash prepare_credentials.sh "${{ secrets.api_key }}" "${{ secrets.api_key_secret }}" "${{ secrets.access_token }}" "${{ secrets.access_token_secret }}"
          #cat api_key.json
          ls
      - name: Generate coverage report
        env: # Or as an environment variable
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run:
          pytest
          #run: |
          #pip install pytest
          #pip install pytest-cov
          #pytest --cov=./ --cov-report=xml
          #- name: Upload coverage to Codecov
          #uses: codecov/codecov-action@v1
          #with:
          #fail_ci_if_error: true
